services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    env_file:
      - ./frontend/.env.dev.list
    depends_on:
      - db_mongodb
      - db_mysql
      - socket_server
      - app_server
    networks:
      - appVirtualNetwork

  app_server:
    build:
      context: backend/applicationServer
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - ./backend/applicationServer/.env.list
    depends_on:
      - db_mongodb
      - db_mysql
      - socket_server
    networks:
      - appVirtualNetwork

  socket_server:
    build:
      context: backend/websocketServer
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/websocketServer/.env.list
    depends_on:
      db_mongodb:
        condition: service_started
      db_mysql:
        condition: service_healthy
    networks:
      - appVirtualNetwork
    # performs data migration on mysql db
    command: ./docker-entrypoint.sh

  db_mysql:
    build:
      context: db
      dockerfile: Dockerfile.mysql
    volumes:
      - mysqlData:/var/lib/mysql:rw
    ports:
      - "3306:3306"
    networks:
      - appVirtualNetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ppass"]
      interval: 10s
      timeout: 5s
      retries: 25

  db_mongodb:
    build:
      context: db
      dockerfile: Dockerfile.mongo
    volumes:
      - mongoData:/data/db:rw
    ports:
      - "27017:27017"
    networks:
      - appVirtualNetwork

networks:
  appVirtualNetwork: {}

volumes:
  mysqlData:
  mongoData:
